HEADER_META=['engagedProb', 'desirePrediction_0', 'desirePrediction_1', 'desirePrediction_2', 'desirePrediction_3', 'desirePrediction_4', 'desirePrediction_5', 'desirePrediction_6', 'desirePrediction_7', 'desirePrediction_8', 'desirePrediction_9', 'desirePrediction_10', 'desirePrediction_11', 'desirePrediction_12', 'desirePrediction_13', 'desirePrediction_14', 'desirePrediction_15', 'desirePrediction_16', 'desirePrediction_17', 'desirePrediction_18', 'desirePrediction_19', 'desirePrediction_20', 'desirePrediction_21', 'desirePrediction_22', 'desirePrediction_23', 'desirePrediction_24', 'desirePrediction_25', 'desirePrediction_26', 'desirePrediction_27', 'desirePrediction_28', 'desirePrediction_29', 'desirePrediction_30', 'desirePrediction_31', 'brakeDisengageProbDEPRECATED', 'gasDisengageProbDEPRECATED', 'steerOverrideProbDEPRECATED', 'desireState_0', 'desireState_1', 'desireState_2', 'desireState_3', 'desireState_4', 'desireState_5', 'desireState_6', 'desireState_7', 'disengagePredictions_t_0', 'disengagePredictions_t_1', 'disengagePredictions_t_2', 'disengagePredictions_t_3', 'disengagePredictions_t_4', 'disengagePredictions_brakeDisengageProbs_0', 'disengagePredictions_brakeDisengageProbs_1', 'disengagePredictions_brakeDisengageProbs_2', 'disengagePredictions_brakeDisengageProbs_3', 'disengagePredictions_brakeDisengageProbs_4', 'disengagePredictions_gasDisengageProbs_0', 'disengagePredictions_gasDisengageProbs_1', 'disengagePredictions_gasDisengageProbs_2', 'disengagePredictions_gasDisengageProbs_3', 'disengagePredictions_gasDisengageProbs_4', 'disengagePredictions_steerOverrideProbs_0', 'disengagePredictions_steerOverrideProbs_1', 'disengagePredictions_steerOverrideProbs_2', 'disengagePredictions_steerOverrideProbs_3', 'disengagePredictions_steerOverrideProbs_4', 'disengagePredictions_brake3MetersPerSecondSquaredProbs_0', 'disengagePredictions_brake3MetersPerSecondSquaredProbs_1', 'disengagePredictions_brake3MetersPerSecondSquaredProbs_2', 'disengagePredictions_brake3MetersPerSecondSquaredProbs_3', 'disengagePredictions_brake3MetersPerSecondSquaredProbs_4', 'disengagePredictions_brake4MetersPerSecondSquaredProbs_0', 'disengagePredictions_brake4MetersPerSecondSquaredProbs_1', 'disengagePredictions_brake4MetersPerSecondSquaredProbs_2', 'disengagePredictions_brake4MetersPerSecondSquaredProbs_3', 'disengagePredictions_brake4MetersPerSecondSquaredProbs_4', 'disengagePredictions_brake5MetersPerSecondSquaredProbs_0', 'disengagePredictions_brake5MetersPerSecondSquaredProbs_1', 'disengagePredictions_brake5MetersPerSecondSquaredProbs_2', 'disengagePredictions_brake5MetersPerSecondSquaredProbs_3', 'disengagePredictions_brake5MetersPerSecondSquaredProbs_4', 'hardBrakePredicted']

HEADER_LONGITUDINALPLAN = ['hasLead', 'fcw', 'modelMonoTime', 'longitudinalPlanSource', 'processingDelay', 'accels_0', 'accels_1', 'accels_2', 'accels_3', 'accels_4', 'accels_5', 'accels_6', 'accels_7', 'accels_8', 'accels_9', 'accels_10', 'accels_11', 'accels_12', 'accels_13', 'accels_14', 'accels_15', 'accels_16', 'speeds_0', 'speeds_1', 'speeds_2', 'speeds_3', 'speeds_4', 'speeds_5', 'speeds_6', 'speeds_7', 'speeds_8', 'speeds_9', 'speeds_10', 'speeds_11', 'speeds_12', 'speeds_13', 'speeds_14', 'speeds_15', 'speeds_16', 'jerks_0', 'jerks_1', 'jerks_2', 'jerks_3', 'jerks_4', 'jerks_5', 'jerks_6', 'jerks_7', 'jerks_8', 'jerks_9', 'jerks_10', 'jerks_11', 'jerks_12', 'jerks_13', 'jerks_14', 'jerks_15', 'jerks_16', 'solverExecutionTime', 'personality']
HEADER_LATERALPLAN = ['mpcSolutionValid', 'desire', 'laneChangeState', 'laneChangeDirection', 'dPathPoints_0', 'dPathPoints_1', 'dPathPoints_2', 'dPathPoints_3', 'dPathPoints_4', 'dPathPoints_5', 'dPathPoints_6', 'dPathPoints_7', 'dPathPoints_8', 'dPathPoints_9', 'dPathPoints_10', 'dPathPoints_11', 'dPathPoints_12', 'dPathPoints_13', 'dPathPoints_14', 'dPathPoints_15', 'dPathPoints_16', 'dPathPoints_17', 'dPathPoints_18', 'dPathPoints_19', 'dPathPoints_20', 'dPathPoints_21', 'dPathPoints_22', 'dPathPoints_23', 'dPathPoints_24', 'dPathPoints_25', 'dPathPoints_26', 'dPathPoints_27', 'dPathPoints_28', 'dPathPoints_29', 'dPathPoints_30', 'dPathPoints_31', 'dPathPoints_32', 'psis_0', 'psis_1', 'psis_2', 'psis_3', 'psis_4', 'psis_5', 'psis_6', 'psis_7', 'psis_8', 'psis_9', 'psis_10', 'psis_11', 'psis_12', 'psis_13', 'psis_14', 'psis_15', 'psis_16', 'curvatures_0', 'curvatures_1', 'curvatures_2', 'curvatures_3', 'curvatures_4', 'curvatures_5', 'curvatures_6', 'curvatures_7', 'curvatures_8', 'curvatures_9', 'curvatures_10', 'curvatures_11', 'curvatures_12', 'curvatures_13', 'curvatures_14', 'curvatures_15', 'curvatures_16', 'curvatureRates_0', 'curvatureRates_1', 'curvatureRates_2', 'curvatureRates_3', 'curvatureRates_4', 'curvatureRates_5', 'curvatureRates_6', 'curvatureRates_7', 'curvatureRates_8', 'curvatureRates_9', 'curvatureRates_10', 'curvatureRates_11', 'curvatureRates_12', 'curvatureRates_13', 'curvatureRates_14', 'curvatureRates_15', 'useLaneLines', 'solverExecutionTime', 'modelMonoTime', 'solverCost']
HEADER_CARSTATE = ['vEgo', 'wheelSpeeds_fl', 'wheelSpeeds_fr', 'wheelSpeeds_rl', 'wheelSpeeds_rr', 'gas', 'gasPressed', 'brake', 'brakePressed', 'steeringAngleDeg', 'steeringTorque', 'steeringPressed', 'cruiseState_enabled', 'cruiseState_speed', 'cruiseState_available', 'cruiseState_speedOffset', 'cruiseState_standstill', 'cruiseState_nonAdaptive', 'cruiseState_speedCluster', 'events_0_name', 'events_0_enable', 'events_0_noEntry', 'events_0_warning', 'events_0_userDisable', 'events_0_softDisable', 'events_0_immediateDisable', 'events_0_preEnable', 'events_0_permanent', 'events_0_overrideLongitudinal', 'events_0_overrideLateral', 'events_1_name', 'events_1_enable', 'events_1_noEntry', 'events_1_warning', 'events_1_userDisable', 'events_1_softDisable', 'events_1_immediateDisable', 'events_1_preEnable', 'events_1_permanent', 'events_1_overrideLongitudinal', 'events_1_overrideLateral', 'events_2_name', 'events_2_enable', 'events_2_noEntry', 'events_2_warning', 'events_2_userDisable', 'events_2_softDisable', 'events_2_immediateDisable', 'events_2_preEnable', 'events_2_permanent', 'events_2_overrideLongitudinal', 'events_2_overrideLateral', 'gearShifter', 'steeringRateDeg', 'aEgo', 'vEgoRaw', 'standstill', 'leftBlinker', 'rightBlinker', 'yawRate', 'genericToggle', 'doorOpen', 'seatbeltUnlatched', 'canValid', 'steeringTorqueEps', 'clutchPressed', 'stockAeb', 'stockFcw', 'espDisabled', 'leftBlindspot', 'rightBlindspot', 'steerFaultTemporary', 'steerFaultPermanent', 'steeringAngleOffsetDeg', 'brakeHoldActive', 'parkingBrake', 'canTimeout', 'fuelGauge', 'accFaulted', 'charging', 'vEgoCluster', 'regenBraking', 'engineRpm', 'carFaultedNonCritical']

HEADER_CALIBRATION=['calStatus', ' calCycle', 'calPerc', 'validBlocks', 'extrinsicMatrix', 'rpyCalib', 'rpyCalibSpread', 'wideFromDeviceEuler','height']


def flatten_data(data, prefix=''):
    """
    Flatten nested dictionaries and lists into a flat dictionary where each key represents the path to the value.
    """
    items = []
    if isinstance(data, dict):
        for key, value in data.items():
            items.extend(flatten_data(value, prefix=prefix + key + '_'))
    elif isinstance(data, list):
        for i, value in enumerate(data):
            items.extend(flatten_data(value, prefix=prefix + str(i) + '_'))
    else:
        items.append((prefix[:-1], data))

    return items


def parse_struct(data,remove_deprecated=False):
    items = flatten_data(data)

    if remove_deprecated:
        items = [x for x in items if 'DEPRECATED' not in x[0]]

    header = [x[0] for x in items]
    values = [x[1] for x in items]
    return header, values
